name: gnome-recipes
version: 2.0.2
summary: GNOME loves to cook
description: |
  Recipes is an easy-to-use application that will help you to discover what to cook
  today, tomorrow, the rest of the week and for your special occasions.

  Recipes comes with a collection of recipes that have been collected by GNOME contributors
  from all over the world. It also lets you store your own recipes and share them with your
  friends.

  The major features of Recipes include:
    * Add and edit your own recipes
    * Share recipes with your friends
    * Export and print shopping lists
    * Adjust quantities based on the number of servings
    * Mark recipes to cook later or add them to your favorites
    * Add notes to recipes
    * Hands-free cooking instruction mode

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-recipes:
    interface: dbus
    bus: session
    name: org.gnome.Recipes

apps:
  gnome-recipes:
    command: desktop-launch gnome-recipes
    plugs:
      - cups-control
      - avahi-observe
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.Recipes.desktop
    environment:
      DISABLE_WAYLAND: 'true'

parts:
  libcanberra:
    source: git://git.0pointer.de/libcanberra
    source-type: git
    plugin: autotools
    configflags:
      - --prefix=/snap/gnome-recipes/current/usr
      - --enable-pulse
      - --enable-gstreamer
      - --enable-gtk3
      - --enable-alsa
      - --disable-oss
    organize:
      snap/gnome-recipes/current/usr: usr
    build-packages:
      - libltdl-dev
      - libasound2-dev
      - libvorbis-dev
      - libgtk-3-dev
      - libtdb-dev
      - libpulse-dev
      - libgstreamer1.0-dev
      - gtk-doc-tools

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform

  gnome-recipes:
    after: [desktop-gnome-platform, libcanberra]
    # temporarily switch to tarball since gitsubmodule URL for 2.0.2
    # no longer works
    # source: https://gitlab.gnome.org/GNOME/recipes.git
    # source-type: git
    # source-tag: 2.0.2
    source: https://download.gnome.org/sources/gnome-recipes/2.0/gnome-recipes-2.0.2.tar.xz
    source-type: tar
    override-build: |
      sed -i.bak -e 's|=org.gnome.Recipes$|=${SNAP}/meta/gui/org.gnome.Recipes.png|g' data/org.gnome.Recipes.desktop.in
      sed -i.bak -e 's|\])$|\], symlink_media: false)|g' help/meson.build
      sed -i.bak -e 's|DATADIR|"/snap/gnome-recipes/current/usr/share"|g' src/gr-appdata.c
      #sed -i.bak -e 's|.flatpak-info|meta/snap.yaml|g' src/gr-utils.c
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/512x512/org.gnome.Recipes.png $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/gnome-recipes/current/usr/share/applications/org.gnome.Recipes.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-recipes/current/usr, -Dautoar=yes]
    organize:
      snap/gnome-recipes/current/usr: usr
    build-packages:
      - gettext
      - itstool
      - libcanberra-dev
      - libgirepository1.0-dev
      - libgspell-1-dev
      - libgoa-1.0-dev
      - libgtk-3-dev
      - libsoup-gnome2.4-dev
      - libgnome-autoar-0-dev
      - libjson-glib-dev
      - libxml2-utils
  libraries:
    plugin: nil
    stage-packages:
      - iso-codes
      - libgnome-autoar-0-0
      - libgoa-1.0-0b
      - libarchive13
    prime:
      - "usr/lib/*/libgnome-autoar-0.so*"
      - "usr/lib/*/libgoa-1.0.so*"
      - "usr/lib/*/libarchive.so*"
